/**
 * Oracle generator for the OSRM integration test.
 *
 * Hits the public OSRM Table service ONCE PER DESTINATION (three separate
 * single-source/single-destination calls) and records the resulting driving
 * distance + time. `OsrmService`, by contrast, asks for all destinations in a
 * single batched call and slices the result by index. The integration test
 * compares the service's batched output against these independently-fetched
 * numbers, which is what proves the index alignment in the service is correct.
 *
 * The public demo server's map data drifts over time, so the saved numbers go
 * stale. When the test starts failing on distance drift, re-run this:
 *
 *   npm run osrm:expected
 *
 * Run with a plain Node that can execute TypeScript (Node >= 22.18 / 24).
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { USER_LOCATION, DESTINATIONS } from '../src/app/osrm/osrm.fixtures.ts';

const BASE = 'https://router.project-osrm.org';

interface OsrmTableResponse {
  code: string;
  distances?: number[][];
  durations?: number[][];
}

interface ExpectedEntry {
  label: string;
  approxMiles: number;
  meters: number;
  seconds: number;
}

async function fetchPair(
  user: { lat: number; lng: number },
  dest: { lat: number; lng: number },
): Promise<{ meters: number; seconds: number }> {
  const coords = [user, dest].map((p) => `${p.lng},${p.lat}`).join(';');
  const url = `${BASE}/table/v1/driving/${coords}?sources=0&annotations=distance,duration`;

  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`OSRM request failed with HTTP ${res.status} for ${coords}`);
  }
  const body = (await res.json()) as OsrmTableResponse;
  if (body.code !== 'Ok' || !body.distances || !body.durations) {
    throw new Error(`OSRM responded with code ${body.code} for ${coords}`);
  }
  // Index 0 is user->user; the single destination is at index 1.
  return { meters: body.distances[0][1], seconds: body.durations[0][1] };
}

async function main(): Promise<void> {
  const entries: ExpectedEntry[] = [];
  for (const dest of DESTINATIONS) {
    const { meters, seconds } = await fetchPair(USER_LOCATION, dest);
    console.log(
      `${dest.label}: ${(meters / 1609.344).toFixed(1)} mi, ${(seconds / 60).toFixed(1)} min`,
    );
    entries.push({ label: dest.label, approxMiles: dest.approxMiles, meters, seconds });
  }

  const output = {
    generatedAt: new Date().toISOString(),
    user: USER_LOCATION,
    note: 'Generated by `npm run osrm:expected`. See osrm.service.integration.spec.ts.',
    expected: entries,
  };

  const outPath = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    'src',
    'app',
    'osrm',
    'osrm.expected.json',
  );
  writeFileSync(outPath, JSON.stringify(output, null, 2) + '\n');
  console.log(`\nWrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
